#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Business/Show.cshtml")]
    public partial class _Views_Business_Show_cshtml : Plum.Web.ApplicationViewBase<Plum.Models.Business>
    {
        public _Views_Business_Show_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Business\Show.cshtml"
  
    ViewBag.Title = "Show";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <h2");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">Settings</h2>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 211), Tuple.Create("\"", 270)
            
            #line 10 "..\..\Views\Business\Show.cshtml"
, Tuple.Create(Tuple.Create("", 218), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Queue.Show(Model.Queues.First().Id))
            
            #line default
            #line hidden
, 218), false)
);

WriteLiteral(" class=\"btn btn-primary btn-lg pull-right\"");

WriteLiteral(" data-loading-overlay=\"true\"");

WriteLiteral(">\r\n                Go To Wait List\r\n            </a>\r\n        </div>\r\n    </div>\r" +
"\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    Business Information (your customers will see this)\r\n     " +
"           </div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n                        <dt>Business Name</dt>\r\n                        <dd>");

            
            #line 24 "..\..\Views\Business\Show.cshtml"
                       Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n                        <dt>Phone Number</dt>\r\n");

            
            #line 26 "..\..\Views\Business\Show.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Business\Show.cshtml"
                         if (Model.HasPhoneNumber())
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <dd>");

            
            #line 28 "..\..\Views\Business\Show.cshtml"
                           Write(Html.PhoneNumber(Model.PhoneNumber));

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n");

            
            #line 29 "..\..\Views\Business\Show.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <dd>None</dd>\r\n");

            
            #line 33 "..\..\Views\Business\Show.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </dl>\r\n\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1259), Tuple.Create("\"", 1306)
            
            #line 36 "..\..\Views\Business\Show.cshtml"
, Tuple.Create(Tuple.Create("", 1266), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Business.Edit(Model.Id))
            
            #line default
            #line hidden
, 1266), false)
);

WriteLiteral(" class=\"btn btn-default btn-block\"");

WriteLiteral(" data-loading-overlay=\"true\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i>\r\n                        Edit Business Information\r\n                    </a" +
">\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    Sign In Information\r\n                </div>\r\n             " +
"   <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n                        <dt>Email Address</dt>\r\n                        <dd>");

            
            #line 51 "..\..\Views\Business\Show.cshtml"
                       Write(Model.Account.EmailAddress);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n                        <dt>Password</dt>\r\n                        <dd>\r\n " +
"                           &#9679;\t&#9679;\t&#9679;\t&#9679;\t&#9679;\t&#9679;\t&#967" +
"9;\t&#9679;\r\n                        </dd>\r\n                    </dl>\r\n          " +
"          <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default btn-block\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i>\r\n                        Edit Sign In Information\r\n                    </a>" +
"\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <d" +
"iv");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    Text Messages\r\n                </div>\r\n                <di" +
"v");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n                        <dt>Welcome Text Message</dt>\r\n                       " +
" <dd><em>");

            
            #line 74 "..\..\Views\Business\Show.cshtml"
                           Write(Model.SampleWelcomeTextMessage());

            
            #line default
            #line hidden
WriteLiteral("</em></dd>\r\n                        <dt>Ready Text Message</dt>\r\n                " +
"        <dd><em>");

            
            #line 76 "..\..\Views\Business\Show.cshtml"
                           Write(Model.SampleReadyTextMessage());

            
            #line default
            #line hidden
WriteLiteral("</em></dd>\r\n                    </dl>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default btn-block\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i>\r\n                        Edit Text Messages\r\n                    </a>\r\n    " +
"            </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
