#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using WaitlistApp;
    using WaitlistApp.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Business/EditorTemplates/BusinessInformationViewModel.cshtml")]
    public partial class _Views_Business_EditorTemplates_BusinessInformationViewModel_cshtml_ : WaitlistApp.Web.ApplicationViewBase<WaitlistApp.ViewModels.Business.BusinessInformationViewModel>
    {
        public _Views_Business_EditorTemplates_BusinessInformationViewModel_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Business\EditorTemplates\BusinessInformationViewModel.cshtml"
Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteAttribute("for", Tuple.Create(" for=\"", 134), Tuple.Create("\"", 164)
            
            #line 5 "..\..\Views\Business\EditorTemplates\BusinessInformationViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 140), Tuple.Create<System.Object, System.Int32>(Html.IdFor(x => x.Name)
            
            #line default
            #line hidden
, 140), false)
);

WriteLiteral(">\r\n        Business Name\r\n        <span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">*</span>\r\n    </label>\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Business\EditorTemplates\BusinessInformationViewModel.cshtml"
Write(Html.TextBoxFor(x => x.Name, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Views\Business\EditorTemplates\BusinessInformationViewModel.cshtml"
Write(Html.LabelFor(x => x.PhoneNumber, "Phone Number"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Business\EditorTemplates\BusinessInformationViewModel.cshtml"
Write(Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control", type = "tel", data_formatter = "phone" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default pull-left\"");

WriteLiteral("\r\n   data-loading-overlay=\"true\"");

WriteLiteral("\r\n   data-ajax-load=\"true\"");

WriteLiteral("\r\n   data-ajax-load-target=\"#BusinessInformationPanel\"");

WriteLiteral("\r\n   data-ajax-load-url=\"");

            
            #line 19 "..\..\Views\Business\EditorTemplates\BusinessInformationViewModel.cshtml"
                  Write(Url.Action(MVC.Business.ShowBusinessInformation(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    Cancel\r\n</a>\r\n<input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Save Changes\"");

WriteLiteral(" class=\"btn btn-primary pull-right\"");

WriteLiteral(" />\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

            
            #line 24 "..\..\Views\Business\EditorTemplates\BusinessInformationViewModel.cshtml"
Write(Html.HttpMethodOverride(HttpVerbs.Put));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 25 "..\..\Views\Business\EditorTemplates\BusinessInformationViewModel.cshtml"
Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
