#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Business/DisplayTemplates/SignInInformationViewModel.cshtml")]
    public partial class _Views_Business_DisplayTemplates_SignInInformationViewModel_cshtml_ : Plum.Web.ApplicationViewBase<Plum.ViewModels.Business.SignInInformationViewModel>
    {
        public _Views_Business_DisplayTemplates_SignInInformationViewModel_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n    <dt>Email Address</dt>\r\n    <dd>");

            
            #line 5 "..\..\Views\Business\DisplayTemplates\SignInInformationViewModel.cshtml"
   Write(Model.EmailAddress);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n    <dt>Password</dt>\r\n    <dd>\r\n        &#9679;\t&#9679;\t&#9679;\t&#9679;\t&" +
"#9679;\t&#9679;\t&#9679;\t&#9679;\r\n    </dd>\r\n</dl>\r\n<a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default btn-block\"");

WriteLiteral("\r\n    data-ajax-load=\"true\"");

WriteLiteral("\r\n    data-ajax-load-target=\"#SignInInformationPanel\"");

WriteLiteral("\r\n    data-ajax-load-url=\"");

            
            #line 14 "..\..\Views\Business\DisplayTemplates\SignInInformationViewModel.cshtml"
                   Write(Url.Action(MVC.Business.EditSignInInformation(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i>\r\n    Edit Sign In Information\r\n</a>");

        }
    }
}
#pragma warning restore 1591
