#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Business/DisplayTemplates/TextMessagesViewModel.cshtml")]
    public partial class _Views_Business_DisplayTemplates_TextMessagesViewModel_cshtml_ : Plum.Web.ApplicationViewBase<Plum.ViewModels.Business.TextMessagesViewModel>
    {
        public _Views_Business_DisplayTemplates_TextMessagesViewModel_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n    <dt>\r\n        Welcome Text Message\r\n    </dt>\r\n    <dd><em>");

            
            #line 7 "..\..\Views\Business\DisplayTemplates\TextMessagesViewModel.cshtml"
       Write(Model.SampleWelcomeMessage);

            
            #line default
            #line hidden
WriteLiteral("</em></dd>\r\n    <dt>Ready Text Message</dt>\r\n    <dd><em>");

            
            #line 9 "..\..\Views\Business\DisplayTemplates\TextMessagesViewModel.cshtml"
       Write(Model.SampleReadyMessage);

            
            #line default
            #line hidden
WriteLiteral("</em></dd>\r\n</dl>\r\n<a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default btn-block\"");

WriteLiteral("\r\n   data-ajax-load=\"true\"");

WriteLiteral("\r\n   data-ajax-load-target=\"#TextMessagesPanel\"");

WriteLiteral("\r\n   data-ajax-load-url=\"");

            
            #line 14 "..\..\Views\Business\DisplayTemplates\TextMessagesViewModel.cshtml"
                  Write(Url.Action(MVC.Business.EditTextMessages(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i>\r\n    Edit Text Messages\r\n</a>");

        }
    }
}
#pragma warning restore 1591
