#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/SignIn.cshtml")]
    public partial class _Views_Account_SignIn_cshtml : Plum.Web.ApplicationViewBase<Plum.ViewModels.Account.SignInViewModel>
    {
        public _Views_Account_SignIn_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Account\SignIn.cshtml"
  
    ViewBag.Title = "Sign In";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n            <h2>Sign In</h2>\r\n            <form");

WriteAttribute("action", Tuple.Create(" action=\"", 214), Tuple.Create("\"", 256)
            
            #line 9 "..\..\Views\Account\SignIn.cshtml"
, Tuple.Create(Tuple.Create("", 223), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.SignIn())
            
            #line default
            #line hidden
, 223), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 10 "..\..\Views\Account\SignIn.cshtml"
           Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 12 "..\..\Views\Account\SignIn.cshtml"
               Write(Html.LabelFor(x => x.EmailAddress, "Email Address"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 13 "..\..\Views\Account\SignIn.cshtml"
               Write(Html.TextBoxFor(x => x.EmailAddress, new { @class = "form-control", type = "email" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 16 "..\..\Views\Account\SignIn.cshtml"
               Write(Html.LabelFor(x => x.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 17 "..\..\Views\Account\SignIn.cshtml"
               Write(Html.PasswordFor(x => x.Password, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 20 "..\..\Views\Account\SignIn.cshtml"
               Write(Html.CheckBoxFor(x => x.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 21 "..\..\Views\Account\SignIn.cshtml"
               Write(Html.LabelFor(x => x.RememberMe, "Remember Me"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Account\SignIn.cshtml"
           Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </form>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
