#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/SignUp.cshtml")]
    public partial class _Views_Account_SignUp_cshtml : Plum.Web.ApplicationViewBase<Plum.ViewModels.Account.SignUpViewModel>
    {
        public _Views_Account_SignUp_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Account\SignUp.cshtml"
  
    ViewBag.Title = "Sign Up";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n            <h2>Sign Up</h2>\r\n            <form");

WriteAttribute("action", Tuple.Create(" action=\"", 216), Tuple.Create("\"", 258)
            
            #line 10 "..\..\Views\Account\SignUp.cshtml"
, Tuple.Create(Tuple.Create("", 225), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.SignUp())
            
            #line default
            #line hidden
, 225), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 11 "..\..\Views\Account\SignUp.cshtml"
           Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 13 "..\..\Views\Account\SignUp.cshtml"
               Write(Html.LabelFor(x => x.BusinessName, "Business Name (your customers will see this)"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 14 "..\..\Views\Account\SignUp.cshtml"
               Write(Html.TextBoxFor(x => x.BusinessName, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 17 "..\..\Views\Account\SignUp.cshtml"
               Write(Html.LabelFor(x => x.EmailAddress, "Email Address (in case you forget your password)"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 18 "..\..\Views\Account\SignUp.cshtml"
               Write(Html.TextBoxFor(x => x.EmailAddress, new { @class = "form-control", type = "email" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 21 "..\..\Views\Account\SignUp.cshtml"
               Write(Html.LabelFor(x => x.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 22 "..\..\Views\Account\SignUp.cshtml"
               Write(Html.PasswordFor(x => x.Password, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Account\SignUp.cshtml"
           Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </form>\r\n            <p>\r\n                <br />\r\n                A" +
"lready have an account? ");

            
            #line 29 "..\..\Views\Account\SignUp.cshtml"
                                    Write(Html.ActionLink("Sign In", MVC.Account.SignIn()));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </p>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
