#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : Plum.Web.ApplicationViewBase<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row jumbo\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <h1");

WriteLiteral(" class=\"big hidden-xs hidden-sm\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 9 "..\..\Views\Home\Index.cshtml"
           Write(Html.ApplicationName());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </h1>\r\n            <h1");

WriteLiteral(" class=\"hidden-md hidden-lg\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 12 "..\..\Views\Home\Index.cshtml"
           Write(Html.ApplicationName());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </h1>\r\n            <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">\r\n                Keep your customers up to date with this FREE service by takin" +
"g advantage of the technology they\'re already using.\r\n            </p>\r\n        " +
"    <p>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 562), Tuple.Create("\"", 602)
            
            #line 18 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 569), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.SignUp())
            
            #line default
            #line hidden
, 569), false)
);

WriteLiteral(" class=\"btn btn-primary btn-lg\"");

WriteLiteral(">\r\n                    Sign Up\r\n                </a>\r\n                <span");

WriteLiteral(" class=\"lead-separator\"");

WriteLiteral(">or</span>\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                    Learn How It Works\r\n                </a>\r\n            </p>" +
"\r\n        </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i>\r\n            </h3>\r\n            <h4");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">Plan Your Staffing</h4>\r\n            <p");

WriteLiteral(" class=\"text-justify\"");

WriteLiteral(@">
                Get accurate wait times based on historical averages to learn when your true busy periods are. Save money by making sure you're not over-staffed. Get average wait times by day of the week
                and trended graphs to help you manage your staff, shorten waits, and increase profits.
            </p>
        </div>
        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-user\"");

WriteLiteral("></i>\r\n            </h3>\r\n            <h4");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">Keep your Host Greeting</h4>\r\n            <p");

WriteLiteral(" class=\"text-justify\"");

WriteLiteral(@">
                You want your host to greet guests upon arrival, and that's hard to do if they're tracking down guests! Table's Ready lets the host stay at their station and not worry about chasing
                customers or collecting abandoned (expensive!) pagers. Make your customers feel welcome with Table's Ready
            </p>
        </div>
        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-cutlery\"");

WriteLiteral("></i>\r\n            </h3>\r\n            <h4");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">Stop Losing Walk Aways</h4>\r\n            <p");

WriteLiteral(" class=\"text-justify\"");

WriteLiteral(@">
                Texting customers frees them from waiting on top of the host stand. Crowds by the front door are big deterrents to potential guests, and there is nothing worse than losing a customer. Table's Ready keeps your doorways clear and your tables full.
            </p>
        </div>
        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-mobile\"");

WriteLiteral("></i>\r\n            </h3>\r\n            <h4");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">Engage Your Patrons</h4>\r\n            <p");

WriteLiteral(" class=\"text-justify\"");

WriteLiteral(@">
                A text can pass on more than ""Your table is ready"" - it's customizable and lets you highlight specials, promote events, or even link to social media pages like Facebook and Twitter. Old pagers were an annoyance, Table's Ready is part of the experience.
            </p>
        </div>
    </div>
</div>

");

        }
    }
}
#pragma warning restore 1591
