#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Business/EditorTemplates/TextMessagesViewModel.cshtml")]
    public partial class _Views_Business_EditorTemplates_TextMessagesViewModel_cshtml_ : Plum.Web.ApplicationViewBase<Plum.ViewModels.Business.TextMessagesViewModel>
    {
        public _Views_Business_EditorTemplates_TextMessagesViewModel_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Business\EditorTemplates\TextMessagesViewModel.cshtml"
Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n<fieldset>\r\n    <legend>Welcome Text Message</legend>\r\n    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-info-circle\"");

WriteLiteral(">\r\n                We\'ll send this message as soon as you add a customer to the l" +
"ist. The message will end with a link for the customer to see their place in lin" +
"e.\r\n            </i>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteAttribute("for", Tuple.Create(" for=\"", 507), Tuple.Create("\"", 551)
            
            #line 14 "..\..\Views\Business\EditorTemplates\TextMessagesViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 513), Tuple.Create<System.Object, System.Int32>(Html.IdFor(x => x.WelcomeTextMessage)
            
            #line default
            #line hidden
, 513), false)
);

WriteLiteral(">\r\n            Message\r\n            <span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">*</span>\r\n        </label>\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\Business\EditorTemplates\TextMessagesViewModel.cshtml"
   Write(Html.TextAreaFor(x => x.WelcomeTextMessage, new { @class = "form-control", rows = "4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</fieldset>\r\n<fieldset>\r\n    <legend>Ready Text Message</legend>\r\n " +
"   <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-info-circle\"");

WriteLiteral(">\r\n                We\'ll send this message when you tap the <em>Send Ready Messag" +
"e</em> button for a customer.\r\n            </i>\r\n        </div>\r\n    </div>\r\n   " +
" <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteAttribute("for", Tuple.Create(" for=\"", 1134), Tuple.Create("\"", 1176)
            
            #line 31 "..\..\Views\Business\EditorTemplates\TextMessagesViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 1140), Tuple.Create<System.Object, System.Int32>(Html.IdFor(x => x.ReadyTextMessage)
            
            #line default
            #line hidden
, 1140), false)
);

WriteLiteral(">\r\n            Message\r\n            <span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">*</span>\r\n        </label>\r\n");

WriteLiteral("        ");

            
            #line 35 "..\..\Views\Business\EditorTemplates\TextMessagesViewModel.cshtml"
   Write(Html.TextAreaFor(x => x.ReadyTextMessage, new { @class = "form-control", rows = "4" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</fieldset>\r\n<a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default pull-left\"");

WriteLiteral("\r\n   data-ajax-load=\"true\"");

WriteLiteral("\r\n   data-ajax-load-target=\"#TextMessagesPanel\"");

WriteLiteral("\r\n   data-ajax-load-url=\"");

            
            #line 41 "..\..\Views\Business\EditorTemplates\TextMessagesViewModel.cshtml"
                  Write(Url.Action(MVC.Business.ShowTextMessages(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    Cancel\r\n</a>\r\n<input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Save Changes\"");

WriteLiteral(" class=\"btn btn-primary pull-right\"");

WriteLiteral(" />\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

            
            #line 46 "..\..\Views\Business\EditorTemplates\TextMessagesViewModel.cshtml"
Write(Html.HttpMethodOverride(HttpVerbs.Put));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 47 "..\..\Views\Business\EditorTemplates\TextMessagesViewModel.cshtml"
Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
