#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using WaitlistApp;
    using WaitlistApp.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Customer/Show.cshtml")]
    public partial class _Views_Customer_Show_cshtml : WaitlistApp.Web.ApplicationViewBase<WaitlistApp.ViewModels.Customer.CustomerViewModel>
    {
        public _Views_Customer_Show_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Customer\Show.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"vertical-alignment-helper\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog vertical-align-center\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    &times;\r\n                </button>\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 14 "..\..\Views\Customer\Show.cshtml"
               Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 14 "..\..\Views\Customer\Show.cshtml"
                            Write(Model.NumberInParty);

            
            #line default
            #line hidden
WriteLiteral(") - ");

            
            #line 14 "..\..\Views\Customer\Show.cshtml"
                                                    Write(Model.Customer.TimeWaited().Humanize());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Views\Customer\Show.cshtml"
           Write(Html.FlashMessage());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Views\Customer\Show.cshtml"
           Write(Html.DisplayForModel());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<script>initAjaxLoadLin" +
"ks(\'#ShowCustomerModal\');</script>\r\n");

        }
    }
}
#pragma warning restore 1591
