#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using WaitlistApp;
    using WaitlistApp.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Queue/ShowCustomer.cshtml")]
    public partial class _Views_Queue_ShowCustomer_cshtml : WaitlistApp.Web.ApplicationViewBase<WaitlistApp.Models.Customer>
    {
        public _Views_Queue_ShowCustomer_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Queue\ShowCustomer.cshtml"
  
    ViewBag.Title = Model.Queue.Business.Name;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <h3>");

            
            #line 8 "..\..\Views\Queue\ShowCustomer.cshtml"
   Write(Model.Queue.Business.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n    <div");

WriteLiteral(" class=\"button-stack\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\Queue\ShowCustomer.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Queue\ShowCustomer.cshtml"
         if (Model.Queue.Business.HasPhoneNumber())
        {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 267), Tuple.Create("\"", 312)
, Tuple.Create(Tuple.Create("", 274), Tuple.Create("tel:", 274), true)
            
            #line 12 "..\..\Views\Queue\ShowCustomer.cshtml"
, Tuple.Create(Tuple.Create("", 278), Tuple.Create<System.Object, System.Int32>(Model.Queue.Business.PhoneNumber
            
            #line default
            #line hidden
, 278), false)
, Tuple.Create(Tuple.Create("", 311), Tuple.Create(")", 311), true)
);

WriteLiteral(" class=\"btn btn-block btn-default\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-phone\"");

WriteLiteral("></i>\r\n            Call ");

            
            #line 14 "..\..\Views\Queue\ShowCustomer.cshtml"
            Write(Model.Queue.Business.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n            <span");

WriteLiteral(" class=\"text-muted hidden-xs\"");

WriteLiteral(">(");

            
            #line 15 "..\..\Views\Queue\ShowCustomer.cshtml"
                                           Write(Html.PhoneNumberDashes(Model.Queue.Business.PhoneNumber));

            
            #line default
            #line hidden
WriteLiteral(")</span>\r\n        </a>\r\n");

            
            #line 17 "..\..\Views\Queue\ShowCustomer.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <form");

WriteAttribute("action", Tuple.Create(" action=\"", 589), Tuple.Create("\"", 659)
            
            #line 18 "..\..\Views\Queue\ShowCustomer.cshtml"
, Tuple.Create(Tuple.Create("", 598), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Customer.DestroyWithUrlToken(Model.UrlToken))
            
            #line default
            #line hidden
, 598), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" data-confirm=\"Are you sure?\"");

WriteLiteral(" data-confirm-prompt=\"Are you sure you want to cancel your place in line?\"");

WriteLiteral(" class=\"btn btn-block btn-default\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-times\"");

WriteLiteral("></i>\r\n                Cancel Place In Line\r\n            </button>\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Views\Queue\ShowCustomer.cshtml"
       Write(Html.HttpMethodOverride(HttpVerbs.Delete));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 24 "..\..\Views\Queue\ShowCustomer.cshtml"
       Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </form>\r\n    </div>\r\n    <br />\r\n    <div");

WriteLiteral(" id=\"customerViewQueueList\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Views\Queue\ShowCustomer.cshtml"
   Write(Html.Partial(MVC.Queue.Views.CustomerViewQueueList, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script>\r\n        window.viewData = {};\r\n        window.viewData.urlToken =" +
" \'");

            
            #line 35 "..\..\Views\Queue\ShowCustomer.cshtml"
                               Write(Model.UrlToken);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        window.viewData.udpateCustomerViewQueueListUrl = \'");

            
            #line 36 "..\..\Views\Queue\ShowCustomer.cshtml"
                                                     Write(Url.Action(MVC.Queue.CustomerViewQueueList(Model.UrlToken)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    </script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1473), Tuple.Create("\"", 1552)
            
            #line 38 "..\..\Views\Queue\ShowCustomer.cshtml"
, Tuple.Create(Tuple.Create("", 1479), Tuple.Create<System.Object, System.Int32>(Html.FileVersionUrl(Links.Content.Scripts.Queue.ShowCustomer_es5_min_js)
            
            #line default
            #line hidden
, 1479), false)
);

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
