#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Queue/CustomerView.cshtml")]
    public partial class _Views_Queue_CustomerView_cshtml : Plum.Web.ApplicationViewBase<Plum.Models.Customer>
    {
        public _Views_Queue_CustomerView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Queue\CustomerView.cshtml"
  
    ViewBag.Title = "CustomerView";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <h3>");

            
            #line 8 "..\..\Views\Queue\CustomerView.cshtml"
   Write(Model.Queue.Business.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n    <div");

WriteLiteral(" class=\"button-stack\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"btn btn-block btn-default\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-phone\"");

WriteLiteral("></i>\r\n            Call The City Brewery\r\n            <span");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">(602-890-3306)</span>\r\n        </button>\r\n        <form");

WriteAttribute("action", Tuple.Create(" action=\"", 395), Tuple.Create("\"", 446)
            
            #line 15 "..\..\Views\Queue\CustomerView.cshtml"
, Tuple.Create(Tuple.Create("", 404), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Queue.CancelPlaceInLine())
            
            #line default
            #line hidden
, 404), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" data-confirm=\"Are you sure?\"");

WriteLiteral(" data-confirm-prompt=\"Are you sure you want to cancel your place in line?\"");

WriteLiteral(" class=\"btn btn-block btn-default\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-times\"");

WriteLiteral("></i>\r\n                Cancel Place In Line\r\n            </button>\r\n");

WriteLiteral("            ");

            
            #line 20 "..\..\Views\Queue\CustomerView.cshtml"
       Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 21 "..\..\Views\Queue\CustomerView.cshtml"
       Write(Html.Hidden(MVC.Queue.CancelPlaceInLineParams.urlToken, Model.UrlToken));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </form>\r\n    </div>\r\n    <br />\r\n    <div");

WriteLiteral(" id=\"customerViewQueueList\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Views\Queue\CustomerView.cshtml"
   Write(Html.Partial(MVC.Queue.Views.CustomerViewQueueList, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script>\r\n        window.viewData = {};\r\n        window.viewData.urlToken =" +
" \'");

            
            #line 32 "..\..\Views\Queue\CustomerView.cshtml"
                               Write(Model.UrlToken);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        window.viewData.udpateCustomerViewQueueListUrl = \'");

            
            #line 33 "..\..\Views\Queue\CustomerView.cshtml"
                                                     Write(Url.Action(MVC.Queue.CustomerViewQueueList(Model.UrlToken)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    </script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1290), Tuple.Create("\"", 1369)
            
            #line 35 "..\..\Views\Queue\CustomerView.cshtml"
, Tuple.Create(Tuple.Create("", 1296), Tuple.Create<System.Object, System.Int32>(Html.FileVersionUrl(Links.Content.Scripts.Queue.CustomerView_es5_min_js)
            
            #line default
            #line hidden
, 1296), false)
);

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
