#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Queue/ManageCustomerModal.cshtml")]
    public partial class _Views_Queue_ManageCustomerModal_cshtml : Plum.Web.ApplicationViewBase<Plum.Models.Customer>
    {
        public _Views_Queue_ManageCustomerModal_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Queue\ManageCustomerModal.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"vertical-alignment-helper\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog vertical-align-center\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"ManageCustomerModal\"");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    &times;\r\n                </button>\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 14 "..\..\Views\Queue\ManageCustomerModal.cshtml"
               Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 14 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                            Write(Model.NumberInParty);

            
            #line default
            #line hidden
WriteLiteral(") ");

            
            #line 14 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                                                  Write(Model.TimeWaited().Humanize());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body button-stack\"");

WriteLiteral(">\r\n");

            
            #line 18 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                 if (string.IsNullOrWhiteSpace(Model.PhoneNumber))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <p>\r\n                        <em>No phone number.</em>\r\n     " +
"               </p>\r\n");

WriteLiteral("                    <button");

WriteLiteral(" class=\"btn btn-block btn-primary\"");

WriteLiteral("  disabled=\"disabled\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-comment\"");

WriteLiteral("></i>\r\n                        Send &quot;Table Ready&quot; Message\r\n            " +
"        </button>\r\n");

            
            #line 27 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <p>\r\n                        <em>");

            
            #line 31 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                       Write(Html.PhoneNumber(Model.PhoneNumber));

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n                    </p>\r\n");

WriteLiteral("                    <button");

WriteLiteral(" class=\"btn btn-block btn-primary\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-comment\"");

WriteLiteral("></i>\r\n                        Send &quot;Table Ready&quot; Message\r\n            " +
"        </button>\r\n");

            
            #line 37 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <form");

WriteAttribute("action", Tuple.Create(" action=\"", 1493), Tuple.Create("\"", 1541)
            
            #line 38 "..\..\Views\Queue\ManageCustomerModal.cshtml"
, Tuple.Create(Tuple.Create("", 1502), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Queue.RemoveCustomer())
            
            #line default
            #line hidden
, 1502), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" data-confirm=\"Are you sure?\"");

WriteLiteral(" data-confirm-prompt=\"Are you sure you want to remove ");

            
            #line 39 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                                                                                                         Write(HttpUtility.HtmlAttributeEncode(Model.Name));

            
            #line default
            #line hidden
WriteLiteral(" from the list?\"");

WriteLiteral(" class=\"btn btn-block btn-default\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">Remove From List</button>\r\n");

WriteLiteral("                    ");

            
            #line 40 "..\..\Views\Queue\ManageCustomerModal.cshtml"
               Write(Html.Hidden(MVC.Queue.RemoveCustomerParams.customerId, Model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Views\Queue\ManageCustomerModal.cshtml"
               Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </form>\r\n                <button");

WriteLiteral(" class=\"btn btn-block btn-default\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">Move to End of List</button>\r\n                ");

WriteLiteral("\r\n");

            
            #line 45 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                 if (Model.LogEntries.Any())
                {

            
            #line default
            #line hidden
WriteLiteral("                    <h5>\r\n                        History\r\n                    </" +
"h5>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"history\"");

WriteLiteral(">\r\n");

            
            #line 51 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                         foreach (var entry in Model.LogEntries.OrderByDescending(x => x.Id))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <p>\r\n                                <i");

WriteAttribute("class", Tuple.Create(" class=\"", 2531), Tuple.Create("\"", 2555)
, Tuple.Create(Tuple.Create("", 2539), Tuple.Create("fa", 2539), true)
            
            #line 54 "..\..\Views\Queue\ManageCustomerModal.cshtml"
, Tuple.Create(Tuple.Create(" ", 2541), Tuple.Create<System.Object, System.Int32>(entry.Icon()
            
            #line default
            #line hidden
, 2542), false)
);

WriteLiteral("></i>\r\n");

WriteLiteral("                                ");

            
            #line 55 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                           Write(entry.Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">");

            
            #line 56 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                                                    Write(entry.Age().Humanize());

            
            #line default
            #line hidden
WriteLiteral(" ago</span>\r\n                            </p>\r\n");

            
            #line 58 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n");

            
            #line 60 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<script>\r\n    initConfirm" +
"ationModals(\'#ManageCustomerModal\');\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
