#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Queue/ManageCustomerModal.cshtml")]
    public partial class _Views_Queue_ManageCustomerModal_cshtml : Plum.Web.ApplicationViewBase<Plum.Models.Customer>
    {
        public _Views_Queue_ManageCustomerModal_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Queue\ManageCustomerModal.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n    <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n        &times;\r\n    </button>\r\n    <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Views\Queue\ManageCustomerModal.cshtml"
   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 11 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                Write(Model.NumberInParty);

            
            #line default
            #line hidden
WriteLiteral(") ");

            
            #line 11 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                                      Write(Model.TimeWaited().Humanize());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </h4>\r\n</div>\r\n<div");

WriteLiteral(" class=\"modal-body button-stack\"");

WriteLiteral(">\r\n    <button");

WriteLiteral(" class=\"btn btn-block btn-primary\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"fa fa-comment\"");

WriteLiteral("></i>\r\n        Send &quot;Table Ready&quot; Message\r\n    </button>\r\n    <form");

WriteAttribute("action", Tuple.Create(" action=\"", 515), Tuple.Create("\"", 563)
            
            #line 19 "..\..\Views\Queue\ManageCustomerModal.cshtml"
, Tuple.Create(Tuple.Create("", 524), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Queue.RemoveCustomer())
            
            #line default
            #line hidden
, 524), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"btn btn-block btn-default\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">Remove From List</button>\r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Views\Queue\ManageCustomerModal.cshtml"
   Write(Html.Hidden(MVC.Queue.RemoveCustomerParams.customerId, Model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 22 "..\..\Views\Queue\ManageCustomerModal.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n    <button");

WriteLiteral(" class=\"btn btn-block btn-default\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">Move to End of List</button>\r\n    ");

WriteLiteral("\r\n");

            
            #line 26 "..\..\Views\Queue\ManageCustomerModal.cshtml"
    
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Queue\ManageCustomerModal.cshtml"
     if (Model.LogEntries.Any())
    {

            
            #line default
            #line hidden
WriteLiteral("        <h5>\r\n            History\r\n        </h5>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"history\"");

WriteLiteral(">\r\n");

            
            #line 32 "..\..\Views\Queue\ManageCustomerModal.cshtml"
            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Queue\ManageCustomerModal.cshtml"
             foreach (var entry in Model.LogEntries)
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 1188), Tuple.Create("\"", 1212)
, Tuple.Create(Tuple.Create("", 1196), Tuple.Create("fa", 1196), true)
            
            #line 35 "..\..\Views\Queue\ManageCustomerModal.cshtml"
, Tuple.Create(Tuple.Create(" ", 1198), Tuple.Create<System.Object, System.Int32>(entry.Icon()
            
            #line default
            #line hidden
, 1199), false)
);

WriteLiteral("></i>\r\n");

WriteLiteral("                    ");

            
            #line 36 "..\..\Views\Queue\ManageCustomerModal.cshtml"
               Write(entry.Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <span");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">");

            
            #line 37 "..\..\Views\Queue\ManageCustomerModal.cshtml"
                                        Write(entry.Age().Humanize());

            
            #line default
            #line hidden
WriteLiteral(" ago</span>\r\n                </p>\r\n");

            
            #line 39 "..\..\Views\Queue\ManageCustomerModal.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");

            
            #line 41 "..\..\Views\Queue\ManageCustomerModal.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
