#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/DisplayTemplates/CustomerViewModel.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_CustomerViewModel_cshtml_ : Plum.Web.ApplicationViewBase<Plum.ViewModels.Customer.CustomerViewModel>
    {
        public _Views_Shared_DisplayTemplates_CustomerViewModel_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
  
    bool customerIsLastInline = Model.Customer.Queue.OrderedCustomers().Last() == Model.Customer;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"modal-body button-stack\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

            
            #line 9 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
            
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
             if (!string.IsNullOrWhiteSpace(Model.Note))
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>\r\n                    Note: <em>");

            
            #line 12 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                         Write(Model.Note);

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n                </p>\r\n");

            
            #line 14 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 15 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
             if (Model.Customer.HasPhoneNumber())
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>\r\n                    <em>");

            
            #line 18 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                   Write(Html.PhoneNumber(Model.PhoneNumber));

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n                </p>\r\n");

            
            #line 20 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                using (Ajax.BeginForm(MVC.Customer.SendReadyMessage(Model.Id), new AjaxOptions { OnBegin = "setLoading", OnComplete = "clearLoading", UpdateTargetId = "ShowCustomerModal" }))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" class=\"btn btn-block btn-primary\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-comment\"");

WriteLiteral("></i>\r\n                        Send &quot;Ready&quot; Message\r\n                  " +
"  </button>\r\n");

            
            #line 26 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
               Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                                             
                }
                using (Ajax.BeginForm(MVC.Customer.SendWelcomeMessage(Model.Id), new AjaxOptions { OnBegin = "setLoading", OnComplete = "clearLoading", UpdateTargetId = "ShowCustomerModal" }))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" class=\"btn btn-block btn-default\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-comment-o\"");

WriteLiteral("></i>\r\n                        Resend &quot;Welcome&quot; Message\r\n              " +
"      </button>\r\n");

            
            #line 34 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
               Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                                             
                }

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default btn-block\"");

WriteLiteral("\r\n                   data-ajax-load=\"true\"");

WriteLiteral("\r\n                   data-ajax-load-target=\"#ShowCustomerModal\"");

WriteLiteral("\r\n                   data-ajax-load-url=\"");

            
            #line 39 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                                  Write(Url.Action(MVC.Customer.SendCustomMessage()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-comment-o\"");

WriteLiteral("></i>\r\n                    Send Text message...\r\n                </a>\r\n");

            
            #line 43 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>\r\n                    <em>No phone number.</em>\r\n             " +
"   </p>\r\n");

            
            #line 49 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <form");

WriteAttribute("action", Tuple.Create(" action=\"", 2154), Tuple.Create("\"", 2206)
            
            #line 50 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 2163), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Customer.Destroy(Model.Id))
            
            #line default
            #line hidden
, 2163), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(" data-loading-overlay=\"true\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" data-confirm=\"Are you sure?\"");

WriteLiteral(" data-confirm-prompt=\"Are you sure you want to remove ");

            
            #line 51 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                                                                                                     Write(HttpUtility.HtmlAttributeEncode(Model.Name));

            
            #line default
            #line hidden
WriteLiteral(" from the list?\"");

WriteLiteral(" class=\"btn btn-block btn-default\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">Remove From List</button>\r\n");

WriteLiteral("                ");

            
            #line 52 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
           Write(Html.HttpMethodOverride(HttpVerbs.Delete));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 53 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
           Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </form>\r\n");

            
            #line 55 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
            
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
             if (!customerIsLastInline)
            {
                using (Ajax.BeginForm(MVC.Customer.MoveToEndOfList(Model.Id), new AjaxOptions { OnBegin = "setLoading", OnComplete = "clearLoading", UpdateTargetId = "ShowCustomerModal" }))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <button");

WriteLiteral(" class=\"btn btn-block btn-default\"");

WriteLiteral(" data-confirm=\"Are you sure?\"");

WriteLiteral(" data-confirm-prompt=\"Are you sure you want to move ");

            
            #line 59 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                                                                                                                                         Write(HttpUtility.HtmlAttributeEncode(Model.Name));

            
            #line default
            #line hidden
WriteLiteral(" to the end of the list?\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">\r\n                        Move to End of List\r\n                    </button>\r\n");

            
            #line 62 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
               Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                                             
                }
            }

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default btn-block\"");

WriteLiteral("\r\n               data-ajax-load=\"true\"");

WriteLiteral("\r\n               data-ajax-load-target=\"#ShowCustomerModal\"");

WriteLiteral("\r\n               data-ajax-load-url=\"");

            
            #line 68 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                              Write(Url.Action(MVC.Customer.Edit(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                Edit Party\r\n            </a>\r\n");

            
            #line 71 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
            
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
             if (Model.Customer.LogEntries.Any())
            {

            
            #line default
            #line hidden
WriteLiteral("                <h5>\r\n                    History\r\n                </h5>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"history\"");

WriteLiteral(">\r\n");

            
            #line 77 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                     foreach (var entry in Model.Customer.LogEntries.OrderByDescending(x => x.Id))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <p>\r\n                            <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3911), Tuple.Create("\"", 3935)
, Tuple.Create(Tuple.Create("", 3919), Tuple.Create("fa", 3919), true)
            
            #line 80 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
, Tuple.Create(Tuple.Create(" ", 3921), Tuple.Create<System.Object, System.Int32>(entry.Icon()
            
            #line default
            #line hidden
, 3922), false)
);

WriteLiteral("></i>\r\n");

WriteLiteral("                            ");

            
            #line 81 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                       Write(entry.Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <span");

WriteLiteral(" class=\"text-muted text-nowrap\"");

WriteLiteral(">");

            
            #line 82 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                                                            Write(entry.Age().Humanize());

            
            #line default
            #line hidden
WriteLiteral(" ago</span>\r\n                        </p>\r\n");

            
            #line 84 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n");

            
            #line 86 "..\..\Views\Shared\DisplayTemplates\CustomerViewModel.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n<script>\r\n    initConfirmationModals(\'#ShowCu" +
"stomerModal\');\r\n    initLoadingOverlays(\'#ShowCustomerModal\');\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
