#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Customer/Edit.cshtml")]
    public partial class _Views_Customer_Edit_cshtml : Plum.Web.ApplicationViewBase<Plum.ViewModels.Customer.CustomerViewModel>
    {
        public _Views_Customer_Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-6 col-md-offset-3\"");

WriteLiteral(">\r\n            <p>\r\n                <strong>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 212), Tuple.Create("\"", 261)
            
            #line 8 "..\..\Views\Customer\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 219), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Queue.Show(Model.QueueId))
            
            #line default
            #line hidden
, 219), false)
);

WriteLiteral(" data-loading-overlay=\"true\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-chevron-left\"");

WriteLiteral("></i>\r\n                        Back to List\r\n                    </a>\r\n          " +
"      </strong>\r\n            </p>\r\n            <h2>Edit Party</h2>\r\n            " +
"<form");

WriteAttribute("action", Tuple.Create(" action=\"", 512), Tuple.Create("\"", 555)
            
            #line 15 "..\..\Views\Customer\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 521), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Customer.Update())
            
            #line default
            #line hidden
, 521), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(" data-loading-overlay=\"true\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 16 "..\..\Views\Customer\Edit.cshtml"
           Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Views\Customer\Edit.cshtml"
           Write(Html.EditorForModel());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-block btn-primary\"");

WriteLiteral(" value=\"Save Changes\"");

WriteLiteral(" />\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Views\Customer\Edit.cshtml"
           Write(Html.HttpMethodOverride(HttpVerbs.Put));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Views\Customer\Edit.cshtml"
           Write(Html.HiddenFor(x => x.QueueId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Views\Customer\Edit.cshtml"
           Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </form>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
