#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Customer/Edit.cshtml")]
    public partial class _Views_Customer_Edit_cshtml : Plum.Web.ApplicationViewBase<Plum.ViewModels.Customer.CustomerViewModel>
    {
        public _Views_Customer_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Customer\Edit.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"vertical-alignment-helper\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog vertical-align-center\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    &times;\r\n                </button>\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">\r\n                    Edit Party\r\n                </h4>\r\n            </div>\r\n   " +
"         <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n");

            
            #line 18 "..\..\Views\Customer\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Customer\Edit.cshtml"
                 using (Ajax.BeginForm(MVC.Customer.Update(), new AjaxOptions { OnBegin = "setLoading", OnComplete = "clearLoading", UpdateTargetId = "ShowCustomerModal" }))
                {
                    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Customer\Edit.cshtml"
               Write(Html.EditorForModel());

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Customer\Edit.cshtml"
                                          

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default pull-left\"");

WriteLiteral("\r\n                       data-loading-overlay=\"true\"");

WriteLiteral("\r\n                       data-ajax-load=\"true\"");

WriteLiteral("\r\n                       data-ajax-load-target=\"#ShowCustomerModal\"");

WriteLiteral("\r\n                       data-ajax-load-url=\"");

            
            #line 25 "..\..\Views\Customer\Edit.cshtml"
                                      Write(Url.Action(MVC.Customer.Show(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                        Cancel\r\n                    </a>\r\n");

WriteLiteral("                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Save Changes\"");

WriteLiteral(" class=\"btn btn-primary pull-right\"");

WriteLiteral(" />\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

            
            #line 30 "..\..\Views\Customer\Edit.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Customer\Edit.cshtml"
               Write(Html.HttpMethodOverride(HttpVerbs.Put));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Customer\Edit.cshtml"
                                                           
                    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Customer\Edit.cshtml"
               Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Customer\Edit.cshtml"
                                             
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<script>initAjaxLoadLinks" +
"(\'#ShowCustomerModal\');</script>\r\n<script>initFormatters(\'#ShowCustomerModal\');<" +
"/script>");

        }
    }
}
#pragma warning restore 1591
