#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using Plum;
    using Plum.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Customer/SendCustomMessage.cshtml")]
    public partial class _Views_Customer_SendCustomMessage_cshtml : Plum.Web.ApplicationViewBase<dynamic>
    {
        public _Views_Customer_SendCustomMessage_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Customer\SendCustomMessage.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"vertical-alignment-helper\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog vertical-align-center\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    &times;\r\n                </button>\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">\r\n                    Send Text Message\r\n                </h4>\r\n            </di" +
"v>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n");

            
            #line 17 "..\..\Views\Customer\SendCustomMessage.cshtml"
                
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Customer\SendCustomMessage.cshtml"
                 using (Ajax.BeginForm(MVC.Customer.SendCustomMessage(), new AjaxOptions { OnBegin = "setLoading", OnComplete = "clearLoading", UpdateTargetId = "ShowCustomerModal" }))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <p>Send a text message to the customer.</p>\r\n     " +
"                       <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"Message\"");

WriteLiteral(">\r\n                                    Message\r\n                                 " +
"   <span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">*</span>\r\n                                </label>\r\n");

WriteLiteral("                                ");

            
            #line 27 "..\..\Views\Customer\SendCustomMessage.cshtml"
                           Write(Html.TextArea(MVC.Customer.SendCustomMessageParams.message, new { @class = "form-control", rows = "3" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"         </div>\r\n");

WriteLiteral("                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default pull-left\"");

WriteLiteral("\r\n                       data-loading-overlay=\"true\"");

WriteLiteral("\r\n                       data-ajax-load=\"true\"");

WriteLiteral("\r\n                       data-ajax-load-target=\"#ShowCustomerModal\"");

WriteLiteral("\r\n                       data-ajax-load-url=\"");

            
            #line 35 "..\..\Views\Customer\SendCustomMessage.cshtml"
                                      Write(Url.Action(MVC.Customer.Show()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                       Cancel\r\n                    </a>\r\n");

WriteLiteral("                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Send\"");

WriteLiteral(" class=\"btn btn-primary pull-right\"");

WriteLiteral(" />\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

            
            #line 40 "..\..\Views\Customer\SendCustomMessage.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Customer\SendCustomMessage.cshtml"
               Write(Html.AntiForgeryToken2());

            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Customer\SendCustomMessage.cshtml"
                                             
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<script>initAjaxLoadLinks" +
"(\'#ShowCustomerModal\');</script>\r\n");

        }
    }
}
#pragma warning restore 1591
