#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Humanizer;
    using WaitlistApp;
    using WaitlistApp.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Business/DisplayTemplates/TextMessagesViewModel.cshtml")]
    public partial class _Views_Business_DisplayTemplates_TextMessagesViewModel_cshtml_ : WaitlistApp.Web.ApplicationViewBase<WaitlistApp.ViewModels.Business.TextMessagesViewModel>
    {
        public _Views_Business_DisplayTemplates_TextMessagesViewModel_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<p");

WriteAttribute("class", Tuple.Create(" class=\"", 66), Tuple.Create("\"", 140)
            
            #line 3 "..\..\Views\Business\DisplayTemplates\TextMessagesViewModel.cshtml"
, Tuple.Create(Tuple.Create("", 74), Tuple.Create<System.Object, System.Int32>(Model.Business.IsNearsTextMessageLimit() ? "text-danger" : null
            
            #line default
            #line hidden
, 74), false)
);

WriteLiteral(">You have sent <strong>");

            
            #line 3 "..\..\Views\Business\DisplayTemplates\TextMessagesViewModel.cshtml"
                                                                                               Write(Model.Business.TextMessagesSent.ToString("N0"));

            
            #line default
            #line hidden
WriteLiteral("</strong> out of <strong>");

            
            #line 3 "..\..\Views\Business\DisplayTemplates\TextMessagesViewModel.cshtml"
                                                                                                                                                                       Write(Model.Business.TextMessageLimit.ToString("N0"));

            
            #line default
            #line hidden
WriteLiteral("</strong> text messages this month.</p>\r\n<dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n    <dt>\r\n        Welcome Text Message\r\n    </dt>\r\n    <dd><em>");

            
            #line 8 "..\..\Views\Business\DisplayTemplates\TextMessagesViewModel.cshtml"
       Write(Model.SampleWelcomeMessage);

            
            #line default
            #line hidden
WriteLiteral("</em></dd>\r\n    <dt>Ready Text Message</dt>\r\n    <dd><em>");

            
            #line 10 "..\..\Views\Business\DisplayTemplates\TextMessagesViewModel.cshtml"
       Write(Model.SampleReadyMessage);

            
            #line default
            #line hidden
WriteLiteral("</em></dd>\r\n</dl>\r\n<a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-default btn-block\"");

WriteLiteral("\r\n   data-ajax-load=\"true\"");

WriteLiteral("\r\n   data-ajax-load-target=\"#TextMessagesPanel\"");

WriteLiteral("\r\n   data-ajax-load-url=\"");

            
            #line 15 "..\..\Views\Business\DisplayTemplates\TextMessagesViewModel.cshtml"
                  Write(Url.Action(MVC.Business.EditTextMessages(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i>\r\n    Edit Text Messages\r\n</a>");

        }
    }
}
#pragma warning restore 1591
